package com.java.moudle.appoint.dto;

import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;


public class SysSubscribeDto implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 84934347694664L;

    /* This code was generated by TableGo tools, mark 1 begin. */
    private String doctorName;//医生名称
    private String professional;//医生职称
    private String hospitalName;//医院名称
    private String deptName; //科室名称
    @JSONField(format="yyyy-MM-dd HH:mm")
    private Date visitTime;//预约时间
    private String name; //就诊人名称
    private String cardNum; //就诊卡号
    private String address; //医院地址
    private String imageUrl; //医生头像
    private String phone; //发送短信的手机号
    
    
	public String getDoctorName() {
		return doctorName;
	}
	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}
	public String getProfessional() {
		return professional;
	}
	public void setProfessional(String professional) {
		this.professional = professional;
	}
	public String getHospitalName() {
		return hospitalName;
	}
	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}
	public String getDeptName() {
		return deptName;
	}
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
	public Date getVisitTime() {
		return visitTime;
	}
	public void setVisitTime(Date visitTime) {
		this.visitTime = visitTime;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getCardNum() {
		return cardNum;
	}
	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
    

}