package com.java.moudle.system.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dba.BaseDomain;

/**
 * 组织机构表(sys_org)
 * 
 * @author ljf
 * @version 1.0.0 2019-11-29
 */
@Entity
@Table(name = "sys_org")
public class SysOrg extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -2355838473980589007L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 机构名称 */
    private String orgName;

    /** 机构代码 */
    private String orgCode;

    /** 上级机构ID */
    private String parentId;

    /** 等级 */
    private BigDecimal orgLevel;

    /** 更新人 */
    private String updateUser;

    /** 更新时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date updateTime;

    /** 是否删除 0 否  1 是 */
    private Integer deleteFlg;

    /** 备注 */
    private String remarks;

    /** 机构编号 */
    private String orgNum;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取机构名称
     * 
     * @return 机构名称
     */
    public String getOrgName() {
        return this.orgName;
    }

    /**
     * 设置机构名称
     * 
     * @param orgName
     *          机构名称
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * 获取机构代码
     * 
     * @return 机构代码
     */
    public String getOrgCode() {
        return this.orgCode;
    }

    /**
     * 设置机构代码
     * 
     * @param orgCode
     *          机构代码
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * 获取上级机构ID
     * 
     * @return 上级机构ID
     */
    public String getParentId() {
        return this.parentId;
    }

    /**
     * 设置上级机构ID
     * 
     * @param parentId
     *          上级机构ID
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取等级
     * 
     * @return 等级
     */
    public BigDecimal getOrgLevel() {
        return this.orgLevel;
    }

    /**
     * 设置等级
     * 
     * @param orgLevel
     *          等级
     */
    public void setOrgLevel(BigDecimal orgLevel) {
        this.orgLevel = orgLevel;
    }

    public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
     * 获取是否删除 0 否  1 是
     * 
     * @return 是否删除 0 否  1 是
     */
    public Integer getDeleteFlg() {
        return this.deleteFlg;
    }

    /**
     * 设置是否删除 0 否  1 是
     * 
     * @param deleteFlg
     *          是否删除 0 否  1 是
     */
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * 获取备注
     * 
     * @return 备注
     */
    public String getRemarks() {
        return this.remarks;
    }

    /**
     * 设置备注
     * 
     * @param remarks
     *          备注
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * 获取机构编号
     * 
     * @return 机构编号
     */
    public String getOrgNum() {
        return this.orgNum;
    }

    /**
     * 设置机构编号
     * 
     * @param orgNum
     *          机构编号
     */
    public void setOrgNum(String orgNum) {
        this.orgNum = orgNum;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}