package com.java.moudle.system.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 角色菜单表(sys_role_menu)
 * 
 * @author ljf
 * @version 1.0.0 2019-11-29
 */
@Entity
@Table(name = "sys_role_menu")
public class SysRoleMenu extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 8310993249897369369L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 角色ID */
    private String roleId;

    /** 菜单ID */
    private String menuId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取角色ID
     * 
     * @return 角色ID
     */
    public String getRoleId() {
        return this.roleId;
    }

    /**
     * 设置角色ID
     * 
     * @param roleId
     *          角色ID
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取菜单ID
     * 
     * @return 菜单ID
     */
    public String getMenuId() {
        return this.menuId;
    }

    /**
     * 设置菜单ID
     * 
     * @param menuId
     *          菜单ID
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}