package com.java.moudle.personal.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dba.BaseDomain;

/**
 * medical_personnel
 * 
 * @author ljf
 * @version 1.0.0 2019-11-29
 */
@Entity
@Table(name = "medical_personnel")
public class MedicalPersonnel extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -3714749979786537710L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private String id;

    /** 真实姓名 */
    private String name;

    /** 性别 */
    private String xb;
    
    /** 身份证号 */
    private String sfzh;

    /** 登录用户id */
    private String userId;

    /** 联系电话 */
    private String phone;

    /** 常住地址-省 */
    private String addressProvince;
    
    /** name */
    @Transient
    private String addressProvinceName;

    /** 常住地址-市 */
    private String addressCity;
    
    /** name */
    @Transient
    private String addressCityName;
    
    /** 常住地址-地区 */
    private String addressRegion;
    
    /** name */
    @Transient
    private String addressRegionName;
    
    /** 常住地址-街道 */
    private String addressStreet;
    
    /** name */
    @Transient
    private String addressStreetName;
    
    /** 详细地址 */
    private String addressDetail;

    /** 默认就诊人 1.是 0否 */
    private String patientSign;

    /** 状态 */
    @Column(name="status", updatable=false)
    private String status;

    /** 更新人 */
    private String updateUser;

    /** 更新时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date updateTime;
    
    @Transient
    private String cardNum;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取真实姓名
     * 
     * @return 真实姓名
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置真实姓名
     * 
     * @param name
     *          真实姓名
     */
    public void setName(String name) {
        this.name = name;
    }

    public String getXb() {
    	return xb;
	}

	public void setXb(String xb) {
    	this.xb = xb;
	}

	/**
     * 获取身份证号
     * 
     * @return 身份证号
     */
    public String getSfzh() {
        return this.sfzh;
    }

    /**
     * 设置身份证号
     * 
     * @param sfzh
     *          身份证号
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    /**
     * 获取登录用户id
     * 
     * @return 登录用户id
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * 设置登录用户id
     * 
     * @param userId
     *          登录用户id
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * 获取联系电话
     * 
     * @return 联系电话
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * 设置联系电话
     * 
     * @param phone
     *          联系电话
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 获取常住地址-省
     * 
     * @return 常住地址-省
     */
    public String getAddressProvince() {
        return this.addressProvince;
    }

    /**
     * 设置常住地址-省
     * 
     * @param addressProvince
     *          常住地址-省
     */
    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince;
    }

    /**
     * 获取常住地址-市
     * 
     * @return 常住地址-市
     */
    public String getAddressCity() {
        return this.addressCity;
    }

    /**
     * 设置常住地址-市
     * 
     * @param addressCity
     *          常住地址-市
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    /**
     * 获取详细地址
     * 
     * @return 详细地址
     */
    public String getAddressDetail() {
        return this.addressDetail;
    }

    /**
     * 设置详细地址
     * 
     * @param addressDetail
     *          详细地址
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    /**
     * 获取默认就诊人 1.是 0否
     * 
     * @return 默认就诊人 1
     */
    public String getPatientSign() {
        return this.patientSign;
    }

    /**
     * 设置默认就诊人 1.是 0否
     * 
     * @param patientSign
     *          默认就诊人 1
     */
    public void setPatientSign(String patientSign) {
        this.patientSign = patientSign;
    }

    /**
     * 获取状态
     * 
     * @return 状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置状态
     * 
     * @param status
     *          状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取更新人
     * 
     * @return 更新人
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * 设置更新人
     * 
     * @param updateUser
     *          更新人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getAddressRegion() {
		return addressRegion;
	}

	public void setAddressRegion(String addressRegion) {
		this.addressRegion = addressRegion;
	}

	public String getAddressStreet() {
		return addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	public String getAddressProvinceName() {
		return addressProvinceName;
	}

	public void setAddressProvinceName(String addressProvinceName) {
		this.addressProvinceName = addressProvinceName;
	}

	public String getAddressCityName() {
		return addressCityName;
	}

	public void setAddressCityName(String addressCityName) {
		this.addressCityName = addressCityName;
	}

	public String getAddressRegionName() {
		return addressRegionName;
	}

	public void setAddressRegionName(String addressRegionName) {
		this.addressRegionName = addressRegionName;
	}

	public String getAddressStreetName() {
		return addressStreetName;
	}

	public void setAddressStreetName(String addressStreetName) {
		this.addressStreetName = addressStreetName;
	}
    /* This code was generated by TableGo tools, mark 2 end. */

	public String getCardNum() {
		return cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}
}