package com.java.moudle.documentGuidelines.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 意见反馈表(feedback)
 * 
 * @author ljf
 * @version 1.0.0 2019-12-19
 */
@Entity
@Table(name = "feedback")
public class Feedback extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6043777372247567189L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 联系方式 */
    @Column(updatable = false)
    private String contactInformation;

    /** 反馈内容 */
    @Column(updatable = false)
    private String content;

    /** 反馈人 */
    @Column(updatable = false)
    private String feedbackUser;

    /** 创建时间 */
    @Column(updatable = false)
    private Date feedbackTime;

    /** 处理人 */
    private String handleUser;

    /** 处理时间 */
    private Date handleTime;

    /** 处理结果 */
    private String handleResult;

    /** 状态 0 创建  1处理完成 */
    private String status;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     *          id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取联系方式
     * 
     * @return 联系方式
     */
    public String getContactInformation() {
        return this.contactInformation;
    }

    /**
     * 设置联系方式
     * 
     * @param contactInformation
     *          联系方式
     */
    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation;
    }

    /**
     * 获取反馈内容
     * 
     * @return 反馈内容
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置反馈内容
     * 
     * @param content
     *          反馈内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取反馈人
     * 
     * @return 反馈人
     */
    public String getFeedbackUser() {
        return this.feedbackUser;
    }

    /**
     * 设置反馈人
     * 
     * @param feedbackUser
     *          反馈人
     */
    public void setFeedbackUser(String feedbackUser) {
        this.feedbackUser = feedbackUser;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getFeedbackTime() {
        return this.feedbackTime;
    }

    /**
     * 设置创建时间
     * 
     * @param feedbackTime
     *          创建时间
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * 获取处理人
     * 
     * @return 处理人
     */
    public String getHandleUser() {
        return this.handleUser;
    }

    /**
     * 设置处理人
     * 
     * @param handleUser
     *          处理人
     */
    public void setHandleUser(String handleUser) {
        this.handleUser = handleUser;
    }

    /**
     * 获取处理时间
     * 
     * @return 处理时间
     */
    public Date getHandleTime() {
        return this.handleTime;
    }

    /**
     * 设置处理时间
     * 
     * @param handleTime
     *          处理时间
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * 获取处理结果
     * 
     * @return 处理结果
     */
    public String getHandleResult() {
        return this.handleResult;
    }

    /**
     * 设置处理结果
     * 
     * @param handleResult
     *          处理结果
     */
    public void setHandleResult(String handleResult) {
        this.handleResult = handleResult;
    }

    /**
     * 获取状态 0 创建  1处理完成
     * 
     * @return 状态 0 创建  1处理完成
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置状态 0 创建  1处理完成
     * 
     * @param status
     *          状态 0 创建  1处理完成
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}