package com.java.moudle.documentGuidelines.domain;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.google.common.util.concurrent.Service.State;
import com.java.until.dba.BaseDomain;

/**
 * 健康科普表(health_educate_info)
 * 
 * @author ljf
 * @version 1.0.0 2019-12-11
 */
@Entity
@Table(name = "health_educate_info")
public class HealthEducateInfo extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3017861257807755326L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private String id;

    /** 发布消息的医院id */
    @Column(updatable = false)
    private String hospitalId;
    
    /** 医院名称 */
    @Transient
    private String hospitalName;
    
    /** 标题 */
    private String title;

    /** 副标题 */
    private String subtitle;

    /** 封面 */
    private String imageUrl;

    /** 内容 */
    private String content;

    /** 状态 1.正常  3.删除 */
    private String status;

    /** 更新人 */
    private String updateUser;

    /** 更新时间 */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(String id) {
        this.id = id;
    }
    
    /**
     * 获取发布消息的医院id
     * 
     * @param id
     *          发布消息的医院id
     */
    public String getHospitalId() {
		return hospitalId;
	}

    /**
     * 设置发布消息的医院id
     * 
     * @param id
     *          发布消息的医院id
     */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId;
	}

	public String getHospitalName() {
		return hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	/**
     * 获取标题
     * 
     * @return 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置标题
     * 
     * @param title
     *          标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取副标题
     * 
     * @return 副标题
     */
    public String getSubtitle() {
        return this.subtitle;
    }

    /**
     * 设置副标题
     * 
     * @param subtitle
     *          副标题
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * 获取封面
     * 
     * @return 封面
     */
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * 设置封面
     * 
     * @param imageUrl
     *          封面
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * 获取内容
     * 
     * @return 内容
     */
	@Lob
	@Basic(fetch = FetchType.EAGER)
	@Column(name="CONTENT", columnDefinition="CLOB", nullable=true)
    public String getContent() {
        return this.content;
    }

    /**
     * 设置内容
     * 
     * @param content
     *          内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取状态 1.正常  3.删除
     * 
     * @return 状态 1
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置状态 1.正常  3.删除
     * 
     * @param status
     *          状态 1
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取更新人
     * 
     * @return 更新人
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * 设置更新人
     * 
     * @param updateUser
     *          更新人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * 获取更新时间
     * 
     * @return 更新时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置更新时间
     * 
     * @param updateTime
     *          更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /* This code was generated by TableGo tools, mark 2 end. */
}