package com.java.moudle.documentGuidelines.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dba.BaseDomain;
import com.java.until.dict.DictUtil;

/**
 * registration_guide
 * 
 * @author ljf
 * @version 1.0.0 2019-11-29
 */
@Entity
@Table(name = "registration_guide")
public class RegistrationGuide extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 4487863389429404020L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private String id;

    /** 标题 */
    private String title;

    /** 副标题 */
    private String subtitle;

    /** 分类id */
    private String classificationid;
    
    /** 分类名 */
    @Transient
    private String classificationName;
    
    /** 内容 */
    private String content;

    /** 状态 */
    @Column(updatable = false)
    private String status;

    /** 更新人 */
    private String updateUser;

    /** 更新时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date updateTime;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubtitle() {
		return subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getClassificationid() {
		return classificationid;
	}

	public void setClassificationid(String classificationid) {
		this.classificationid = classificationid;
		this.classificationName = DictUtil.getDictValue("1003", classificationid);
	}

	public String getClassificationName() {
		return classificationName;
	}

	public void setClassificationName(String classificationName) {
		this.classificationName = classificationName;
	}

	
}