package com.java.moudle.documentGuidelines.domain;
import java.sql.Clob;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 关于我们表(sys_about_us)
 * 
 * @author ljf
 * @version 1.0.0 2019-12-11
 */
@Entity
@Table(name = "sys_about_us")
public class SysAboutUs extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -597727230347975186L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 关于我们 */
    private String content;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取关于我们
     * 
     * @return 关于我们
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置关于我们
     * 
     * @param content
     *          关于我们
     */
    public void setContent(String content) {
        this.content = content;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}