package com.java.moudle.documentGuidelines.domain;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dba.BaseDomain;

/**
 * 友情链接表(sys_links)
 * 
 * @author ljf
 * @version 1.0.0 2019-12-11
 */
@Entity
@Table(name = "sys_links")
public class SysLinks extends BaseDomain implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1961009522391035888L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private String id;

    /** 链接名称 */
    private String name;

    /** 链接地址 */
    private String linkUrl;
    
    /** 状态 1 正常 3 删除 */
    @Column(name = "status", updatable = false)
    private String status;
    
    /** 创建时间 */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取链接名称
     * 
     * @return 链接名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置链接名称
     * 
     * @param name
     *          链接名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取链接地址
     * 
     * @return 链接地址
     */
    public String getLinkUrl() {
        return this.linkUrl;
    }

    /**
     * 设置链接地址
     * 
     * @param linkUrl
     *          链接地址
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}