package com.java.moudle.appoint.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.java.moudle.webservice.domain.DoctorInfo;
import com.java.until.dba.BaseDomain;

/**
 * subscribe_result
 * 
 * @author ljf
 * @version 1.0.0 2019-11-29
 */
@Entity
@Table(name = "subscribe_result")
public class SubscribeResult extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -4712582359989936831L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private String id;

    /** 预约id */
    private String subscribeId;

    /** 医生id */
    @Transient
    private String doctorId;
    
    /** 评价类型 */
    private String evaluationType = "";

    /** 评价内容 */
    private String evaluationContent = "";

    /** 投诉原因 */
    private String complaintContent = "";

    /** 创建人 */
    private String createUser;

    /** 创建时间 */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 对应的医生信息 */
    @Transient
    private DoctorInfo doctorInfo;
    
    /** 就诊人姓名 */
    @Transient
    private String jzrName;
    
    /** 预约时间 */
    @Transient
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date yyTime;
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取预约id
     * 
     * @return 预约id
     */
    public String getSubscribeId() {
        return this.subscribeId;
    }

    /**
     * 设置预约id
     * 
     * @param subscribeId
     *          预约id
     */
    public void setSubscribeId(String subscribeId) {
        this.subscribeId = subscribeId;
    }

    public String getEvaluationType() {
		return evaluationType;
	}

	public String getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	public void setEvaluationType(String evaluationType) {
		this.evaluationType = evaluationType;
	}

	public String getEvaluationContent() {
		return evaluationContent;
	}

	public void setEvaluationContent(String evaluationContent) {
		this.evaluationContent = evaluationContent;
	}

	/**
     * 获取投诉原因
     * 
     * @return 投诉原因
     */
    public String getComplaintContent() {
        return this.complaintContent;
    }

    /**
     * 设置投诉原因
     * 
     * @param complaintContent
     *          投诉原因
     */
    public void setComplaintContent(String complaintContent) {
        this.complaintContent = complaintContent;
    }

    /**
     * 获取创建人
     * 
     * @return 创建人
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * 设置创建人
     * 
     * @param createUser
     *          创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public DoctorInfo getDoctorInfo() {
		return doctorInfo;
	}

	public void setDoctorInfo(DoctorInfo doctorInfo) {
		this.doctorInfo = doctorInfo;
	}

	public String getJzrName() {
		return jzrName;
	}

	public void setJzrName(String jzrName) {
		this.jzrName = jzrName;
	}

	public Date getYyTime() {
		return yyTime;
	}

	public void setYyTime(Date yyTime) {
		this.yyTime = yyTime;
	}
    /* This code was generated by TableGo tools, mark 2 end. */
}